#!/bin/sh

##########################################################################################
#
#   Author: Igor Androsov 2022
#
##########################################################################################

# Create new Scratch org environment for development testing and load test data
# Set input prameter values

ORG_ALIAS="$1"
# Get input for ORG active days with default to 30 days
ACTIVEDAYS="${2:-30}"

echo "--- START DEPLOYMENT FOR: $ORG_ALIAS"
echo "--- New ORG will be active for: $ACTIVEDAYS"
# Set user alias from org name
TRLUSER="${ORG_ALIAS}-user"

# Create new scratch org 30 days max
sfdx force:org:create --setdefaultusername --setalias $ORG_ALIAS --definitionfile config/project-scratch-def.json -d $ACTIVEDAYS || { echo 'Scratch org create failed' ; exit 1; }

# Create test user
sfdx force:user:create --setalias $TRLUSER --definitionfile config/user-def.json || { echo 'Scratch org User create failed' ; exit 1; }
sfdx force:user:display -u $TRLUSER

# Push source
sfdx force:source:push -u $ORG_ALIAS || { echo 'Source push failed' ; exit 1; }

# Assign Permission Set to users

# Push sample data
# sfdx force:data:tree:import -u ggw --plan test-data/export-ggw-plan.json

# Run Tests - optional step

# Open new org
#sfdx force:org:open -u $ORG_ALIAS