#!/bin/sh

##########################################################################################
#
#   Author: Igor Androsov 2023
#
##########################################################################################

# Create new Scratch org environment for development testing and load test data
# Set input prameter values

ORG_ALIAS="$1"
# Get input for ORG active days with default to 30 days
ACTIVEDAYS="${2:-30}"

echo "--- START DEPLOYMENT FOR: $ORG_ALIAS"
echo "--- New ORG will be active for: $ACTIVEDAYS"
# Set user alias from org name
TESTUSER="${ORG_ALIAS}-user"

# Create new scratch org 30 days max
sf org create scratch --target-dev-hub labsDevHub --alias $ORG_ALIAS --definition-file config/project-scratch-def.json --set-default --duration-days $ACTIVEDAYS || { echo 'Scratch org create failed' ; exit 1; }

# Create test user
# sfdx force:user:create --setalias $TESTUSER --definitionfile config/user-def.json || { echo 'Scratch org User create failed' ; exit 1; }
# sfdx force:user:display -u $TESTUSER

# Push source
echo "--- PUSH SOURCE FOR: $ORG_ALIAS"
sf project deploy start --target-org $ORG_ALIAS || { echo 'Source push failed' ; exit 1; }
# To pull source from scxratch org
# sf project retrieve start --target-org $ORG_ALIAS

# Assign Permission Set to users
echo "--- ASSIGN PERMISSIONS FOR: $ORG_ALIAS"
sf org assign permset --name GGW_User_Permissions --target-org $ORG_ALIAS || { echo 'User permission failed' ; exit 1; }

# Push sample data
echo "--- INSERT SAMPLE DATA FOR: $ORG_ALIAS"
sf data import tree --plan test-data/sample-data-GGW_Section__c-GGW_Content_Block__c-plan.json --target-org $ORG_ALIAS

# sfdx force:data:tree:import --target-org $ORG_ALIAS --plan test-data/export-section-GGW_Section__c-plan.json
#sfdx force:data:tree:import -u ggw --plan test-data/export-section-GGW_Section__c-plan.json
# Run Tests - optional step

# Open new org
#sf org open --target-org $ORG_ALIAS
echo "--- END DEPLOYMENT FOR: $ORG_ALIAS"