name: Feature Build

on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_GITHUB }}
jobs:
  unit_tests:
    name: 'Deploy Code and Run Apex Tests'
    runs-on: Ubuntu-latest
    steps:
        # Install Salesforce CLI
        - name: 'Install Salesforce CLI'
          run: |
              npm install @salesforce/cli --location=global
              nodeInstallPath=$(npm config get prefix)
              echo "$nodeInstallPath/bin" >> $GITHUB_PATH
              sf --version

        # Checkout the source code
        - name: 'Checkout source code'
          uses: actions/checkout@v4

        # Store secret for dev hub
        - name: 'Populate auth file with DEV_HUB_AUTH_URL secret'
          shell: bash
          run: |
              echo ${{ secrets.DEV_HUB_AUTH_URL}} > ./DEV_HUB_AUTH_URL.txt
              secretFileSize=$(wc -c "./DEV_HUB_AUTH_URL.txt" | awk '{print $1}')
              if [ $secretFileSize == 1 ]; then
                  echo "Missing DEV_HUB_AUTH_URL secret. Is this workflow running on a fork?";
                  exit 1;
              fi

        # Authenticate dev hub
        - name: 'Authenticate Dev Hub'
          run: sf org login sfdx-url -f ./DEV_HUB_AUTH_URL.txt -a devhub -d

        # Remove auth file
        - name: 'Remove auth file'
          run: rm -f ./DEV_HUB_AUTH_URL.txt
        
        # Install Python
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        #Install CumulusCI
        - name: Install CumulusCI
          run: |
            python -m pip install -U pip
            pip install cumulusci
        #Use CCI to deploy and test feature
        - name: Deploy and Run Tests
          run: |
            cci flow run ci_feature --org dev --delete-org